title: "Tianyue Yao"
author: "Tianyue Yao"
description: "MFE student @ Cornell University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "About Me"}
  - {file: "Yao.Tianyue (3).pdf", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ty325@cornell.edu"}
  - {title: Github, icon: github, url: "https://github.com/ty325"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/tianyue_yao/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
